REM RUN THIS FILE PREVIOUS TO NOTEBOOK EXECUTION IN CMD
REM THIS ACTIVATE ONE ISOLATED ENVIRONMENT FOR THE NOTEBOOK EXECUTION
REM EVERY TIME WE OPEN THE PROJECT WE NEED TO RUN THE ACTIVATE COMMAND

REM CREATED FILE WITH LIBRARIES AND VERSIONS TO INSTALL: requirements.txt

python -m venv venv

.\venv\Scripts\activate 

pip install -r requirements.txt
